### ISSUE TITLE
Support IE11

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/philly-ward-leaders#158]

**Comment by timwis** [comment]
Note that v1 does not support IE11 -- there's an issue with the CSS animation of the baseball cards.

**Comment by timwis** [comment]
Apparently IE doesn't support `<foreignObject>`, which means we can't add the "Details" button to the back of the baseball card, unless we can figure out some way to do that with svg.

Apart from that, the baseball cards are showing up as rather tiny, but otherwise it seems to work fine. This defect is definitely significant though.

**Comment by pwolanin** [comment]
yeah, IE is dead
