### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/philly-ward-leaders#169]
The little CfP liberty bell perhaps?

**Comment by pwolanin** [comment]
or the c70 one?  Asking the c70 people

**Comment by pwolanin** [comment]
I think that would be a good choice, but so far have not found a better version than what's in the repo.  That's a little low-res.  Will ask again if Chris can find one.

**Comment by pwolanin** [comment]
Added a version I got from Kat
