### ISSUE TITLE
Add info about deployment and/or figure out how switch to github pages

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/philly-ward-leaders#173]
We needed to use surge since github pages doesn't support html5 history. Need to document how that works, and how to take control of it.

**Comment by pwolanin** [comment]
this is maybe an answer to how we can switch to deploy to github pages: https://www.smashingmagazine.com/2016/08/sghpa-single-page-app-hack-github-pages/

**Comment by pwolanin** [comment]
This is deployed to gh-pages now, but still need to implement the hack linkedd above

**Comment by pwolanin** [comment]
The redirect with history is workign, so let's call this complete in terms of handoff
