### ISSUE TITLE
Collapsed menu colors wrong on firefox

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/philly-ward-leaders#176]
When the navigation menu is collapsed (on mobile), the menu's background color is incorrect on firefox.
<img width="245" alt="screen shot 2017-12-30 at 12 13 53" src="https://user-images.githubusercontent.com/761444/34457067-012d2c5a-ed5b-11e7-8c07-089416f5aeb0.png">

**Comment by pwolanin** [comment]
fixed in another issue
