### ISSUE TITLE
Deploy failure should break travis build

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/philly-ward-leaders#187]
[A deployment failed last night](https://travis-ci.org/CodeForPhilly/philly-ward-leaders/builds/560098154) but travis showed it as passing. Click the "Deploying application" line to expand the log and see it says `Invalid token`. Not sure why this didn't fail the build but it should have, which would trigger a notification.

It would be worthwhile to just move the deployment to netlify (which would let us take advantage of their forms and FaaS too, as well as free https), though we're still limited to 1 user on the free tier there.

**Comment by pwolanin** [comment]
travis seems inactive at the moment, and switch to github pages.
