### ISSUE TITLE
On mobile/narrow the hamburger menu background color makes the text invisible until hover

### ISSUE THREAD

**Issue by pwolanin** [CodeForPhilly/philly-ward-leaders#236]
Background color issue

[ward-leaders-menu_2022-08-02.pdf](https://github.com/CodeForPhilly/philly-ward-leaders/files/9246843/ward-leaders-menu_2022-08-02.pdf)

**Comment by ST215** [comment]
Pull Request opened for this issue: https://github.com/CodeForPhilly/philly-ward-leaders/pull/244

**Comment by pwolanin** [comment]
deployed this a while ago
